
version: '2'


services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"


  postgres:
    image: postgres:9.6.3
    environment:
      PGDATA: "/var/lib/postgresql/data/pgsql"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: "noaa_stations"
    volumes:
      - "/var/lib/postgresql/data/pgsql"


  node:
    build: .
    environment:
      NODE_ENV: "production"
      DATABASE_HOST: "dbhost"
      DATABASE_PORT: "5432"
      VIRTUAL_HOST: ${HOSTNAME}
      DATABASE_UN: "pguser"
      DATABASE_PW: ${POSTGRES_PW}
      DATABASE_NAME: "noaa_stations"
    volumes:
      - "./:/usr/src/app"
    links:
      - "postgres:dbhost"
