
version: '3'


services:

  postgres:
    image: postgres:9.6.9
    environment:
      PGDATA: "/var/lib/postgresql/data/pgsql"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: "noaa_stations"
      POSTGRES_PORT: "5432"
    ports:
      - 5432
    volumes:
      - "/var/lib/postgresql/data/pgsql"


  service:
    expose:
      - "8888"
    build: .
    environment:
      NODE_ENV: "production"
      DATABASE_HOST: dbhost
      DATABASE_PORT: "5432"
      DATABASE_UN: "pguser"
      DATABASE_PW: ${POSTGRES_PW}
      DATABASE_NAME: "noaa_stations"
    links:
      - "postgres:dbhost"
